### ISSUE TITLE
glmpca error on real data

### ISSUE THREAD

**Issue by EliseAld** [willtownes/scrna2019#3]
Hello,
I am really interested in your method and wanted to try and use glmPCA on the data from Guo et al. 2018 (10.1038/s41591-018-0045-3) that consists of immune cells from lung tumor sequenced with Smart-Seq2
When I run glmpca on the whole raw data, I keep getting this error:

glmpca(matrix,L=5,fam="mult",verbose=T,penalty=1)
[1] "Iteration: 1 | deviance=1.993e+10"
Error in (ig$grad) %*% U[, k] : 
  requires numeric/complex matrix/vector arguments

I removed the empty rows/columns. Do you know where it comes from ?

Thanks for the help !

**Comment by willtownes** [comment]
Hi Elise, thanks for your interest. First of all, we do not recommend running GLM-PCA on non-UMI datasets such as those produced by SMART-Seq2. The reason is these data contain additional noise due to PCR amplification that is not well-described by the distributional assumptions of GLM-PCA. We are currently working on a normalization method to make it possible to analyze these data with GLM-PCA so stay tuned!

That having been said, the function should not be throwing the error you report so I will try to help debug it for you. Here are some things to try:
1. Try renaming your data matrix something other than "matrix" since that is a class name. I like to use X, Y, or m for the data matrix.
2. Let's say your data matrix is called "Y". can you tell me the result of `class(Y)` and `mode(Y)`
3. Try running glmpca with fam="poi" instead of fam="mult".
4. Try increasing the penalty from 1 to say 10 or 50.
It's totally possible we made a mistake somewhere in the code so thanks for pointing this out so we can fix it!

**Comment by EliseAld** [comment]
Oh I didn't realize that it was not adapted for non-UMI, thanks for mentionning it.

Regarding my error, and looking at your detailed answer, I understand that I was using the wrong data format : I was inputting the algorithm with a data frame instead of with a matrix, so now it works!

Thank you so much for the help!

**Comment by willtownes** [comment]
I'm glad it worked out!

Note to self- maybe put in as.matrix() at start of glmpca to avoid this confusing users in the future.

**Comment by willtownes** [comment]
Committed the as.matrix() fix to [glmpca R package](https://github.com/willtownes/glmpca/commit/f462af658150974bd8ecedcc461b0700950a79b8)
